[project]
name = "notification-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "pika>=1.3.2",
    "python-dotenv>=1.1.0",
    "uvicorn>=0.34.2",
]
